project:
  type: website
  output-dir: docs

website:
  title: "Course Title"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/chefs-kiss/ML_J2026
        text: GitHub
    style: docked
    contents:
    - section: "Course Information"
      contents:
        - href: index.qmd
          text: Home
        - href: schedule.qmd
          text: Schedule
        - href: support.qmd
          text: Support
        - href: https://github.com/chefs-kiss/ML_J2026/discussions
          text: Forum
    - section: "Tips and Tricks"
      contents:
        - href: course_information/github_tricks.qmd
          text: Using Github
    - section: "Homework"
      contents:
        - href: homework/hw1.qmd
          text: HW1
    - section: "Labs"
      contents:
        - href: labs/lab1.qmd
          text: Lab1
    - section: "Semester Project"
      contents:
        - href: project/project_overview.qmd
          text: Overview
        - href: project/PC1.qmd
          text: PC1

format:
  html:
    theme: vapor
    # css: styles.css
    toc: true

execute:
  freeze: auto

