project:
  type: website
  output-dir: docs

website:
  title: "AI Literacy <br> in Education"

  search:
    type: textbox

  navbar:
    background: primary
    search: true

    left:

      - text: Bookclub
        menu:
          - href: discussions/schedule.qmd
            text: Schedule
          - href: discussions/discussion1.qmd
            text: Session1
          - href: discussions/discussion2.qmd
            text: Session2
          - href: discussions/discussion3.qmd
            text: Session3

      - href: survey/
        text: Quantifying Readiness

      - href: assessments/
        text: Reassessing Assessments

      - text: About
        menu:
          - href: information/people.qmd
            text: People
          - href: information/resources.qmd
            text: Resources

    right:
      - icon: github
        href: https://github.com/chefs-kiss/ai_literacy

format:
  html:
    theme: yeti  #yeti #materia #lux #sandstone #spacelab #vapor   #litera
    #css: styles.css
    toc: true

execute:
  freeze: auto

