project:
  type: website
  output-dir: docs

website:
  title: "AI Literacy <br> in Education"

  search:
    type: textbox

  navbar:
    background: primary
    search: true

    left:

      - href: discussions/schedule.qmd 
        text: Schedule

      - href: discussions/discussion1.qmd
        text: Session 1

      - href: discussions/discussion2.qmd
        text: Session 2

      - href: discussions/discussion3.qmd
        text: Session 3 

      - href: information/resources.qmd
        text: Resources

     # - href: survey/
    #    text: Quantifying Readiness

     # - href: assessments/
      #  text: Reassessing Assessments

      

    right:
      - href: information/people.qmd
        text: People
            
      - icon: github
        href: https://github.com/chefs-kiss/ai_literacy

format:
  html:
    theme: yeti  #yeti #materia #lux #sandstone #spacelab #vapor   #litera #themes here: https://bootswatch.com/
    #css: styles.css
    toc: true

execute:
  freeze: auto

