project:
  type: website
  output-dir: docs

website:
  title: "AI Literacy in Education"
  search:
    type: textbox
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: house
        href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/chefs-kiss/ai_literacy
        text: GitHub
    style: docked
    contents:
    - section: "Moderated Discussions"
      contents:
        - href: discussions/schedule.qmd
          text: Schedule
        - href: discussions/discussion1.qmd
          text: Discussion 1
    - section: "Quantifying Engagement"
      contents:
        - href: survey/
          text: Overview
    - section: "Reassessing Assessments"
      contents:
        - href: assessments/
          text: Overview
    - section: "About"
      contents:
        - href: information/resources.qmd
          text: Resources
        - href: information/people.qmd
          text: People

format:
  html:
    theme: yeti  #yeti #materia #lux #sandstone #spacelab #vapor   #litera
    #css: styles.css
    toc: true

execute:
  freeze: auto

